---
sidebar: sidebar 
permalink: concept-aiq-digital-advisor.html 
keywords: concepts, active iq digital advisor, ontap 
summary: 'Active IQ デジタルアドバイザは"BlueXP UIに統合されているため"1つの画面でONTAP クラスタの操作"セキュリティ"パフォーマンスを最適化できます' 
---
= Digital Advisorを使用してクラスタを最適化します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
https://www.netapp.com/services/support/active-iq/["Digital Advisor"^] （旧称Active IQ ）は、ONTAP クラスタの操作、セキュリティ、パフォーマンスを1つの画面で最適化できるように、BlueXP UIに統合されています。



== の機能

Digital Advisorを使用して、ストレージシステムの全体的なステータス、システムの健全性に関する概要、インベントリ、計画、アップグレード、重要な分析情報を監視リストレベルで確認できます。

* ストレージシステムの健常性を分析し、最適化できます
* ストレージシステムのすべてのリスクと、リスクを軽減するための対処方法に関する分析情報を取得できます
* を表示して、ストレージデバイスのパフォーマンスを分析します パフォーマンスデータのグラフ形式
* 容量の 90% を超えたシステムまたはを超えたシステムに関する詳細を確認できます 容量の使用率が 90% に近づいています
* 期限切れのハードウェアおよびソフトウェアに関する情報を取得します または、今後 6 か月以内に期限切れに近いものとします
* ストレージシステムソフトウェアをアップグレードし、 Ansible で ONTAP ファームウェアを更新します




== サポート対象の ONTAP システム

Digital Advisorは、NSSアカウント内のすべてのオンプレミスONTAP システムとCloud Volumes ONTAP システムに関する情報を提供します。



== コスト

このサービスはBlueXPで無料でご利用いただけます。



== Digital AdvisorがBlueXPとどのように連携するか

を参照してください https://docs.netapp.com/us-en/active-iq/digital-advisor-integration-with-bluexp.html["Digital Advisorのドキュメント"^] を参照してください。
