---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, system manager, unsupported features 
summary: 既知の制限事項は、このリリースの製品でサポートされていないプラットフォーム、デバイス、機能、または製品と正しく相互運用できない機能を特定します。これらの制限事項を慎重に確認してください 
---
= 既知の制限
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
既知の制限事項は、このリリースの製品でサポートされていないプラットフォーム、デバイス、機能、または製品と正しく相互運用できない機能を特定します。これらの制限事項を慎重に確認してください



== ASA R2システムに関連する制限事項

NetApp ASA R2システムを検出して作業環境を開くと、System Managerに直接移動します。

ASA R2システムでは、他の管理オプションは使用できません。[標準]ビューを使用したり、BlueXPサービスを有効にしたりすることはできません。

https://docs.netapp.com/us-en/asa-r2/index.html["ASA R2システムの詳細"^]



== サポート対象外のクラスタです

SAML認証が設定されたオンプレミスのONTAP クラスタはBlueXPではサポートされません。



== System Managerの制限事項

System Managerの次の機能は、BlueXPではサポートされません。

* クラスタセットアップ
+
オンプレミスのONTAP クラスタで管理IPアドレスを設定し、管理パスワードを設定したら、BlueXPでクラスタを検出できます。

* ロールベースアクセス制御（コネクタのみ）
+
コネクタを使用してオンプレミスのONTAP クラスタを検出して管理する場合、System Managerからロールベースアクセス制御はサポートされません。検出プロセスで、管理者クレデンシャルの入力を求められます。これらのクレデンシャルは、System Managerから実行されるすべての処理に使用されます。

+
直接検出オプションを使用すると、作業環境を開くたびにONTAP クレデンシャルを使用してログインするように求められます。

* BlueXPのバックアップとリカバリ（Cloud Backup）のアクティブ化
+
System ManagerからBlueXPのバックアップとリカバリを実行するには、クラスタのバージョンが9.13.1である必要があります。

+
コネクタを使用してクラスタを検出しなかった場合、System Manager（アドバンストビュー）でバックアップとリカバリを有効にすることはできません。ただし、オンプレミスのクラスタでバックアップとリカバリをBlueXPから直接有効にすることもできます。 https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html["開始方法をご確認ください"^]

* オンデマンドアップグレード
+
クラスタのバージョンがONTAP 9.9.1以前の場合、ファームウェアとソフトウェアのオンデマンドアップグレードは実行できません。

+
コネクタがない場合は、ローカルマシンからは更新できず、BlueXPを使用してアクセスできるサーバからのみ更新できます。

* グローバル検索
* ユーザインターフェイスの設定

