---
sidebar: sidebar 
permalink: task-discovering-ontap.html 
keywords: ontap, cluster, discover, manage, discovering, fas, aff, discover onprem, discover aff cluster, discover cluster, add cluster, active iq, digital wallet 
summary: BlueXPでオンプレミスのONTAP クラスタを検出すると、ONTAP System Manager（BlueXPで利用可能）を使用してボリュームの管理や高度な管理を開始できます。 
---
= オンプレミスのONTAP クラスタを検出
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXPからオンプレミスのONTAP クラスタを検出すると、ONTAP System Manager（BlueXPから入手可能）を使用してボリュームの管理や高度な管理を開始できます。



== 検出と管理のオプション

BlueXPには、オンプレミスのONTAP クラスタを検出して管理するための2つの方法があります。

コネクタを介した検出:: このオプションでは、次の機能を使用してONTAP 8.3以降を実行するクラスタを管理できます。
+
--
* 標準ビュー：基本的なボリューム処理を提供します
* Advancedビュー：System Manager（ONTAP 9.10.0以降でサポート）を使用した管理を提供します。
* BlueXPサービスとの統合。データレプリケーション、バックアップとリカバリ、データの分類、データ階層化を実現します


このオプションにはコネクタが必要です。コネクタは、クラウドプロバイダまたはオンプレミスにインストールできます。

--
直接検出:: このオプションを使用すると、ONTAP 9.12.1以降を実行するクラスタをSystem Managerで管理できます。他の管理オプションはありません。標準ビューは使用できず、データサービスを有効にすることもできません。
+
--
このオプションにはコネクタは必要ありません。

BlueXPサービスに接続されている9.12.1以降を実行するオンプレミスONTAP クラスタのSystem Managerにアクセスすると、BlueXPからクラスタを直接管理するように求められます。このプロンプトを実行すると、BlueXPで直接検出オプションを使用してクラスタが検出されます。

--


検出されたクラスタは、BlueXP Canvasで作業環境として使用できます。

後で他の検出オプションを使用する場合は、Canvas上の別の作業環境としてオンプレミスクラスタを検出する必要があります。そのあとで、もう一方の作業環境を削除することもできます。



== 要件

オンプレミスのONTAP クラスタを検出する前に、次の要件を満たしていることを確認してください。



=== 一般的な要件

* BlueXPを使い始めました。これにはログインとアカウントの設定が含まれます。
+
https://docs.netapp.com/us-en/bluexp-setup-admin/concept-overview.html["BlueXPの使用を開始する方法について説明します"^]

* クラスタ管理IPアドレスとadminユーザアカウントのパスワードが必要です。
* BlueXPはHTTPSを使用してONTAP クラスタを検出しましたカスタムファイアウォールポリシーを使用する場合は、ONTAP クラスタがポート443経由のインバウンドHTTPSアクセスを許可する必要があります。
+
デフォルトの「 mgmt 」ファイアウォールポリシーでは、すべての IP アドレスからの着信 HTTPS アクセスが許可されます。このデフォルトポリシーを変更した場合、または独自のファイアウォールポリシーを作成した場合は、 HTTPS プロトコルをそのポリシーに関連付けて、 Connector ホストからのアクセスを有効にする必要があります。





=== コネクタの検出と管理の要件

* オンプレミスクラスタでONTAP 8.3以降が実行されている必要があります。
* コネクタは、クラウドプロバイダまたはオンプレミスにインストールする必要があります。
+
コールドデータをクラウドに階層化する場合は、コールドデータの階層化先に基づいてコネクタの要件を確認してください。

+
** https://docs.netapp.com/us-en/bluexp-setup-admin/concept-connectors.html["コネクタについて説明します"^]
** https://docs.netapp.com/us-en/bluexp-setup-admin/task-managing-connectors.html["コネクタ間の切り替え"^]
** https://docs.netapp.com/us-en/bluexp-tiering/concept-cloud-tiering.html["BlueXPの階層化機能の詳細をご確認ください"^]


* コネクタホストが、ポート 443 経由のアウトバウンド HTTPS アクセスを許可する必要があります。
+
コネクタがクラウドにある場合、すべてのアウトバウンド通信は事前定義されたセキュリティグループによって許可されます。





=== 直接的な検出と管理の要件

* オンプレミスクラスタでONTAP 9.12.1以降が実行されている必要があります。
* クラスタは、BlueXPサービスへのインバウンドおよびアウトバウンド接続を備えている必要があります。
+
\ https://cloudmanager.cloud.netapp.com/ontap-service/check-service-connection

* BlueXPコンソールにアクセスするために使用するコンピュータには、プライベートネットワーク内の他のリソースへの接続方法と同様に、オンプレミスのONTAP クラスタへのネットワーク接続が必要です。




== クラスタを検出します

BlueXPのキャンバスからオンプレミスのONTAP クラスタを検出できます。検出プロセスを開始すると、BlueXPで次のようにクラスタが検出されます。

* ONTAP クラスタに接続しているアクティブなコネクタがある場合、BlueXPはそのコネクタを使用してクラスタを検出および管理します。
* コネクタがない場合やコネクタがONTAP クラスタに接続されていない場合は、BlueXPで自動的に検出と管理の直接オプションが使用されます。


.手順
. ナビゲーションメニューから、*ストレージ>キャンバス*を選択します。
. キャンバスページで、*作業環境の追加*をクリックし、*オンプレミス*を選択します。
. オンプレミスのONTAP の横にある*検出*を選択します。
. [Discover_page]で、クラスタ管理IPアドレス、および管理者ユーザアカウントのパスワードを入力します。
. クラスタを（コネクタなしで）直接検出する場合は、*[クレデンシャルを保存する]*を選択します。
+
このオプションを選択した場合は、作業環境を開くたびにクレデンシャルを再入力する必要はありません。これらのクレデンシャルはBlueXPユーザにのみ関連付けられます。アカウント内の他のユーザーが使用するために保存されることはありません。

. [検出]*を選択します。
+
コネクタがなく、BlueXPからIPアドレスにアクセスできない場合は、コネクタを作成するように求められます。



.結果
BlueXPはクラスタを検出し、それをキャンバス上の作業環境として追加します。これで、クラスタの管理を開始できます。

* link:task-manage-ontap-direct.html["直接検出されたクラスタを管理する方法について説明します"]
* link:task-manage-ontap-connector.html["コネクタを使用して検出されたクラスタを管理する方法について説明します"]

